### ISSUE TITLE
Clean Scrolls.esp gives a warning

### ISSUE THREAD

**Issue by MoonshineIndustries** [Tyler799/Morrowind-2020#119]
> One of the files that "Clean Scrolls.esp" is dependent on has changed since the last save.
This may result in errors. Saving again will clear this message but not necessarily fix any errors.

Is this safe to ignore? It's from the mod [Potions and Scrolls.](http://mw.modhistory.com/download-35-2339)

Edit: I resaved in the construction set and it appears that it has not problems.

**Comment by Tyler799** [comment]
Generally when you encounter something like this, you should run the save cleaning method the guide outlines.

Really, anytime you update, add, or remove mods.

**Comment by MoonshineIndustries** [comment]
This warning came up when I started the game, as it first loads the plugins not when I load or start a game.

**Comment by Tyler799** [comment]
Hmm. I think that has to do with a mod's masters being outdated then. It's a fairly easy fix using Wrye bash. Just something the author forgot to do.
