### ISSUE TITLE
Tes3cmd multipatch appears to be largely useless.

### ISSUE THREAD

**Issue by MoonshineIndustries** [Tyler799/Morrowind-2020#124]
I was looking at my load order in [tes3view](https://github.com/TES5Edit/TES5Edit/releases) and it appears that the multipatch isn't good at all. It only has 3 records that are pretty much the same as its last overwritten plugin, so no actual conflict resolution where mods adding new things aren't overwritten. 

It seems we largely depend on the load order in this game. Are there some better tools to make patches, except for waiting for tes3edit to release and make manual ones?

**Comment by coolnamebro** [comment]
Tes3Merge should work.
