### ISSUE TITLE
Missing Helmet(?) Meshes on Inquisitors in Ministry of Truth

### ISSUE THREAD

**Issue by Warrof** [Tyler799/Morrowind-2020#141]
![Morrowind 2020-04-18 10 00 22 341](https://user-images.githubusercontent.com/21962742/79644804-178a3b00-8160-11ea-9278-12fccbae173e.png)
So yeah, that's Immersion Breaking.  

I don't know what the problem is yet.  Everything I've read says that it's an MSGO problem... This guide doesn't use that, or it's a better bodies or better clothes problem.  Thought I'd post it here for now since I don't have time to hunt down a fix right now.

Will kill one later and figure out what is missing.

**Comment by Tyler799** [comment]
The guide just had some significant changes in the last few days, so I'm not positive if the issue is new or old. If you can find the specific helmet I may be able to track it down.

**Comment by Warrof** [comment]
Will do.  

I used the 2019 version of this guide.

**Comment by Warrof** [comment]
It's the Inquisitor's Mask
![Morrowind 2020-04-18 13 32 18 407](https://user-images.githubusercontent.com/21962742/79670850-b1f77800-817a-11ea-96f7-5ded75e50842.png)

Model Load Error: Meshes\INqMask\INq_head.nif cannot load file in Meshes\INqMask\INq_head.nif.
Will use the default object Marker_Error.NIF.
Model Load Error: Meshes\INqMask\INq_Mask_mesh.nif cannot load file in Meshes\INqMask\INq_Mask_mesh.nif.
Will use the default object Marker_Error.NIF.
Model Load Error: Meshes\INqMask\INq_head2.nif cannot load file in Meshes\INqMask\INq_head2.nif.
Will use the default object Marker_Error.NIF.
Model Load Error: Meshes\INqMask\INq_Mask_mesh2.nif cannot load file in Meshes\INqMask\INq_Mask_mesh2.nif.
Will use the default object Marker_Error.NIF.
Texture Load Error!: icons\Inq Mask\Inq Mask Ic.tga
Texture "Textures\menu_exitgame.tga" count 5.
Texture "Textures\menu_options.tga" count 5.
Texture "Textures\menu_return.tga" count 5.
Texture "Data Files\textures\rrw\w_ref.dds" count 3.
Texture "Textures\menu_loadgame.tga" count 5.
Texture "Data Files\Textures\tx_c_robeextra01t_c_jewel_g.dds" count 3.
Texture "Textures\_land_default.tga" count 3.
Texture "Data Files\Textures\indoril_gm.dds" count 51.
Texture "Data Files\textures\painmw\goldcoin01_nm.dds" count 3.
Texture "Textures\menu_savegame.tga" count 4.
Texture "Textures\menu_newgame.tga" count 5.
Texture "Data Files\Textures\menu_thin_border_bottom.dds" count 2.

**Comment by Warrof** [comment]
Changing to the newer Complete Version of Better Clothes did nothing.

I'm guessing now that one of the armor mods is getting messed up.  Will Troubleshoot more later.

**Comment by Warrof** [comment]
Finally got around to looking at this.
![2020-05-14](https://user-images.githubusercontent.com/21962742/81972716-db6bbe00-95d7-11ea-9b91-e7b01b180aa1.png)

The meshes literally don't exist in the virtual folders.

**Comment by Warrof** [comment]
Finally got around to looking at this.
![2020-05-14 (2)](https://user-images.githubusercontent.com/21962742/81972806-02c28b00-95d8-11ea-9d49-ddd95dfa36d6.png)

The Missing Meshes literally don't exist within MO2's virtual files.

**Comment by Warrof** [comment]
Problem Fixed.  Had to drag the files from the Data Files/Data Files folders to Meshes, Textures, and Icons respectively.
