### ISSUE TITLE
XE FixedFuncEmu.fx does not currently compile.

### ISSUE THREAD

**Issue by Tromador** [Tyler799/Morrowind-2020#153]
Per the title. A version of this shader ships with XE 0.11.6 - Neither the shipped version, nor the downloaded version from the link in the guide (these seem on cursory inspection to be the same with some different parameters) will compile. When attempting to add the shader, it XE throws the error "That shader does not currently compile."

It is likely that fixing any compile error is beyond the purview of the guide author, nevertheless, the recommendation should probably be removed from the guide.

**Comment by Tyler799** [comment]
If anyone wants to make a pull request to fix these, I'll approve it. I'm not doing much manual maintenance of the guide right now.
