### ISSUE TITLE
Orcish armor chest piece is invisible

### ISSUE THREAD

**Issue by SolidMoose96** [Tyler799/Morrowind-2020#160]
I'm not sure what mod is causing this issue, but the orcish armor does not show a texture. Any NPCs that are wearing it have an invisible torso until the armor is removed. Any info for a fix is appreciated.

**Comment by RAINZFOXX** [comment]
There's a problem with the DeFemm patch that comes with Better Morrowind Armor. This is what causes it. You can find a fix for it here: https://forums.nexusmods.com/index.php?/topic/990511-better-morrowind-armor/page-7#entry8861911

**Comment by Tyler799** [comment]
Fixed with recent commit.
